### PR TITLE
created get_mediator_id query and added it to the example code

### PR DESCRIPTION
**Pull request by nhuebel**
CF. #31

### CODE REVIEW

**Comment by blumenthal** [comment]
It does not work on my system: 

```
######################  GET MEDIATOR ID  #########################
[swm_zyre_client_donkey1] send_json_message: message = {"metamodel": "sherpa_mgs", "type": "query_mediator_uuid", "model": "http://kul/query_mediator_uuid.json", "payload": {"UID": "4654d244-483a-1069-d149-4872954f13e3"}}:
[swm_zyre_client_donkey1] WHISPER EDDC46F684731D86EB27DF2F1C41929F donkey1 {"metamodel": "sherpa_mgs", "type": "mediator_uuid", "model": "http://kul/mediator_uuid.json", "payload": {"UID": "4654d244-483a-1069-d149-4872954f13e3", "remote": "5361A42892015454E0B1F232529430DC", "local": "EDDC46F684731D86EB27DF2F1C41929F"}}
[swm_zyre_client_donkey1] Timeout! No query answer received.
[swm_zyre_client_donkey1] Stopping zyre node.
[swm_zyre_client_donkey1] Destroying component.
[�] Received no reply for mediator_id query.

```
Is it correct that the Mediator whispers?

**Comment by nhuebel** [comment]
I forgot to push the change in the mediator. It is up to date now.

**Comment by blumenthal** [comment]
Now it works.

**Comment by blumenthal** [comment]
The result E1250FCB442082E1B8856066A615C26F is not a UUID!

```
 {"UID": "15a914e4-4eb1-2743-a988-cffde20b8ec7", "remote": "E1250FCB442082E1B8856066A615C26F", "local": "65937F503B709942803289B21EFD1099"} 
ID of mediator = E1250FCB442082E1B8856066A615C26F
```

**Pull request merged**
